package OAFS;
// Generated 03-Oct-2017 13:20:33 by Hibernate Tools 4.3.1

/**
 * BrBasicRptId generated by hbm2java
 */
public class BrBasicRptId  implements java.io.Serializable {


     private int id;
     private int userProprietaryId;

    public BrBasicRptId() {
    }

    public BrBasicRptId(int id, int userProprietaryId) {
       this.id = id;
       this.userProprietaryId = userProprietaryId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserProprietaryId() {
        return this.userProprietaryId;
    }
    
    public void setUserProprietaryId(int userProprietaryId) {
        this.userProprietaryId = userProprietaryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BrBasicRptId) ) return false;
		 BrBasicRptId castOther = ( BrBasicRptId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUserProprietaryId()==castOther.getUserProprietaryId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUserProprietaryId();
         return result;
   }   


}


