package OAFS;
// Generated 15-Nov-2017 12:02:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CoreLocation generated by hbm2java
 */
public class CoreLocation  implements java.io.Serializable {


     private int coreRepoId;
     private String name;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private String countryCode;

    public CoreLocation() {
    }

	
    public CoreLocation(int coreRepoId) {
        this.coreRepoId = coreRepoId;
    }
    public CoreLocation(int coreRepoId, String name, BigDecimal latitude, BigDecimal longitude, String countryCode) {
       this.coreRepoId = coreRepoId;
       this.name = name;
       this.latitude = latitude;
       this.longitude = longitude;
       this.countryCode = countryCode;
    }
   
    public int getCoreRepoId() {
        return this.coreRepoId;
    }
    
    public void setCoreRepoId(int coreRepoId) {
        this.coreRepoId = coreRepoId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }




}


