package OAFS;
// Generated 13-Aug-2017 15:27:21 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * JmArticle generated by hbm2java
 */
@XmlRootElement(name = "JM_article")
@XmlAccessorType(XmlAccessType.FIELD)
public class JmArticle implements java.io.Serializable
{

    private int jmId;
    private String name;
    private String ids;
    private String journalTitle;
    private String publisher;
    private String workflowComplete;

    public JmArticle()
    {
    }

    public JmArticle(int jmId)
    {
        this.jmId = jmId;
    }

    public JmArticle(int jmId, String name, String ids, String journalTitle,
            String publisher, String workflowComplete)
    {
        this.jmId = jmId;
        this.name = name;
        this.ids = ids;
        this.journalTitle = journalTitle;
        this.publisher = publisher;
        this.workflowComplete = workflowComplete;
    }

    public int getJmId()
    {
        return this.jmId;
    }

    public void setJmId(int jmId)
    {
        this.jmId = jmId;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getIds()
    {
        return this.ids;
    }

    public void setIds(String ids)
    {
        this.ids = ids;
    }

    public String getJournalTitle()
    {
        return this.journalTitle;
    }

    public void setJournalTitle(String journalTitle)
    {
        this.journalTitle = journalTitle;
    }

    public String getPublisher()
    {
        return this.publisher;
    }

    public void setPublisher(String publisher)
    {
        this.publisher = publisher;
    }

    public String getWorkflowComplete()
    {
        return this.workflowComplete;
    }

    public void setWorkflowComplete(String workflowComplete)
    {
        this.workflowComplete = workflowComplete;
    }

}
