package OAFS;
// Generated 13-Aug-2017 15:27:21 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * JmInvoice generated by hbm2java
 */
@XmlRootElement(name = "JM_invoice")
@XmlAccessorType(XmlAccessType.FIELD)
public class JmInvoice implements java.io.Serializable
{

    private int jmInvoiceId;
    private String name;
    private String passedToFinance;
    private String paymentStatus;
    private String paymentMethod;
    private String invoiceFileName;

    public JmInvoice()
    {
    }

    public JmInvoice(int jmInvoiceId)
    {
        this.jmInvoiceId = jmInvoiceId;
    }

    public JmInvoice(int jmInvoiceId, String name, String passedToFinance,
            String paymentStatus, String paymentMethod, String invoiceFileName)
    {
        this.jmInvoiceId = jmInvoiceId;
        this.name = name;
        this.passedToFinance = passedToFinance;
        this.paymentStatus = paymentStatus;
        this.paymentMethod = paymentMethod;
        this.invoiceFileName = invoiceFileName;
    }

    public int getJmInvoiceId()
    {
        return this.jmInvoiceId;
    }

    public void setJmInvoiceId(int jmInvoiceId)
    {
        this.jmInvoiceId = jmInvoiceId;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getPassedToFinance()
    {
        return this.passedToFinance;
    }

    public void setPassedToFinance(String passedToFinance)
    {
        this.passedToFinance = passedToFinance;
    }

    public String getPaymentStatus()
    {
        return this.paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus)
    {
        this.paymentStatus = paymentStatus;
    }

    public String getPaymentMethod()
    {
        return this.paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod)
    {
        this.paymentMethod = paymentMethod;
    }

    public String getInvoiceFileName()
    {
        return this.invoiceFileName;
    }

    public void setInvoiceFileName(String invoiceFileName)
    {
        this.invoiceFileName = invoiceFileName;
    }

}
