package OAFS;
// Generated 30-Oct-2017 14:59:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OaDoiLocation generated by hbm2java
 */
public class OaDoiLocation  implements java.io.Serializable {


     private OaDoiLocationId id;
     private String version;
     private String evidence;
     private String hostType;
     private Byte isBest;
     private String license;
     private Date updated;
     private String url;
     private String urlForLandingPage;
     private String urlForPdf;
     private Byte isOa;
     private Byte journalIsOa;
     private String journalName;
     private String journalPublisher;

    public OaDoiLocation() {
    }

	
    public OaDoiLocation(OaDoiLocationId id) {
        this.id = id;
    }
    public OaDoiLocation(OaDoiLocationId id, String version, String evidence, String hostType, Byte isBest, String license, Date updated, String url, String urlForLandingPage, String urlForPdf, Byte isOa, Byte journalIsOa, String journalName, String journalPublisher) {
       this.id = id;
       this.version = version;
       this.evidence = evidence;
       this.hostType = hostType;
       this.isBest = isBest;
       this.license = license;
       this.updated = updated;
       this.url = url;
       this.urlForLandingPage = urlForLandingPage;
       this.urlForPdf = urlForPdf;
       this.isOa = isOa;
       this.journalIsOa = journalIsOa;
       this.journalName = journalName;
       this.journalPublisher = journalPublisher;
    }
   
    public OaDoiLocationId getId() {
        return this.id;
    }
    
    public void setId(OaDoiLocationId id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public String getEvidence() {
        return this.evidence;
    }
    
    public void setEvidence(String evidence) {
        this.evidence = evidence;
    }
    public String getHostType() {
        return this.hostType;
    }
    
    public void setHostType(String hostType) {
        this.hostType = hostType;
    }
    public Byte getIsBest() {
        return this.isBest;
    }
    
    public void setIsBest(Byte isBest) {
        this.isBest = isBest;
    }
    public String getLicense() {
        return this.license;
    }
    
    public void setLicense(String license) {
        this.license = license;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getUrlForLandingPage() {
        return this.urlForLandingPage;
    }
    
    public void setUrlForLandingPage(String urlForLandingPage) {
        this.urlForLandingPage = urlForLandingPage;
    }
    public String getUrlForPdf() {
        return this.urlForPdf;
    }
    
    public void setUrlForPdf(String urlForPdf) {
        this.urlForPdf = urlForPdf;
    }
    public Byte getIsOa() {
        return this.isOa;
    }
    
    public void setIsOa(Byte isOa) {
        this.isOa = isOa;
    }
    public Byte getJournalIsOa() {
        return this.journalIsOa;
    }
    
    public void setJournalIsOa(Byte journalIsOa) {
        this.journalIsOa = journalIsOa;
    }
    public String getJournalName() {
        return this.journalName;
    }
    
    public void setJournalName(String journalName) {
        this.journalName = journalName;
    }
    public String getJournalPublisher() {
        return this.journalPublisher;
    }
    
    public void setJournalPublisher(String journalPublisher) {
        this.journalPublisher = journalPublisher;
    }




}


