package OAFS;
// Generated 30-Oct-2017 14:59:01 by Hibernate Tools 4.3.1



/**
 * OaDoiLocationId generated by hbm2java
 */
public class OaDoiLocationId  implements java.io.Serializable {


     private String doi;
     private String id;

    public OaDoiLocationId() {
    }

    public OaDoiLocationId(String doi, String id) {
       this.doi = doi;
       this.id = id;
    }
   
    public String getDoi() {
        return this.doi;
    }
    
    public void setDoi(String doi) {
        this.doi = doi;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OaDoiLocationId) ) return false;
		 OaDoiLocationId castOther = ( OaDoiLocationId ) other; 
         
		 return ( (this.getDoi()==castOther.getDoi()) || ( this.getDoi()!=null && castOther.getDoi()!=null && this.getDoi().equals(castOther.getDoi()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDoi() == null ? 0 : this.getDoi().hashCode() );
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         return result;
   }   


}


